"""Lifecycle helpers for the autonomous-mining Hermes cron job.

`botcoin_autostart` and `botcoin_autostop` programmatically create / remove a
cron job that fires ``hermes-botcoin-mine`` with ``no_agent=True`` on a fixed
schedule. The job runs an installed shell wrapper (written here on demand)
under ``$HERMES_HOME/scripts/botcoin-miner.sh`` so the user has a stable,
auditable entry point — they can ``cat`` the script, edit it, replace it,
or version-control it.

A daily attempt counter is maintained at::

    $HERMES_HOME/.botcoin/attempts-YYYY-MM-DD.count

…so the cost ceiling (``BOTCOIN_MAX_ATTEMPTS_PER_DAY``) survives process
restarts and is decoupled from cron-output filenames.
"""

from __future__ import annotations

import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

JOB_NAME = "BOTCOIN miner"
SCRIPT_BASENAME = "botcoin-miner.sh"
COUNTER_DIR_NAME = ".botcoin"


# ---------------------------------------------------------------------------
# Hermes-home discovery (works inside Hermes runtime AND in tests)


def _hermes_home() -> Path:
    """Return ``$HERMES_HOME`` (or its default) without importing Hermes.

    When running inside Hermes we could ``from hermes_constants import
    get_hermes_home``, but doing the discovery locally keeps this module
    importable from tests without monkey-patching.
    """
    custom = os.environ.get("HERMES_HOME")
    if custom:
        return Path(custom).expanduser().resolve()
    return Path.home() / ".hermes"


def _scripts_dir() -> Path:
    p = _hermes_home() / "scripts"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _counter_dir() -> Path:
    p = _hermes_home() / COUNTER_DIR_NAME
    p.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(p, 0o700)
    except OSError:
        pass
    return p


def _today_counter_path() -> Path:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return _counter_dir() / f"attempts-{today}.count"


# ---------------------------------------------------------------------------
# Daily attempt counter — used by hermes-botcoin-mine to enforce the ceiling


def read_today_count() -> int:
    p = _today_counter_path()
    try:
        return int(p.read_text().strip() or "0")
    except (FileNotFoundError, ValueError):
        return 0


def increment_today_count() -> int:
    """Atomic-ish increment using a tmp-file rename. Returns the new value."""
    p = _today_counter_path()
    current = read_today_count()
    new = current + 1
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(str(new))
    os.replace(tmp, p)
    return new


def daily_ceiling() -> int:
    """Read ``BOTCOIN_MAX_ATTEMPTS_PER_DAY`` (env or default 100)."""
    raw = (os.environ.get("BOTCOIN_MAX_ATTEMPTS_PER_DAY") or "").strip()
    try:
        v = int(raw) if raw else 100
    except ValueError:
        v = 100
    return max(1, v)


# ---------------------------------------------------------------------------
# Wrapper script


_WRAPPER_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by hermes-botcoin's botcoin_autostart tool.
# Path: {script_path}
# Edits to this file persist (autostart will not overwrite a customized script
# unless --reset-script is passed).
#
# Cost ceiling: BOTCOIN_MAX_ATTEMPTS_PER_DAY (default 100). Enforcement lives
# inside hermes-botcoin-mine — this wrapper just exec's it.

set -euo pipefail

# Pull the user's env (~/.hermes/.env) so VENICE_API_KEY / BOTCOIN_MINER_KEY /
# etc. are available even when Hermes' cron tick spawns us with a stripped env.
if [ -f "${{HERMES_HOME:-$HOME/.hermes}}/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "${{HERMES_HOME:-$HOME/.hermes}}/.env"
  set +a
fi

exec hermes-botcoin-mine \\
  --solver "{solver}" \\
{model_line}  --max-attempts 1 \\
  --quiet
"""


def _write_wrapper_script(*, solver: str, model: str | None, force: bool = False) -> Path:
    path = _scripts_dir() / SCRIPT_BASENAME
    if path.exists() and not force:
        return path
    model_line = f'  --model "{model}" \\\n' if model else ""
    body = _WRAPPER_TEMPLATE.format(
        script_path=str(path), solver=solver, model_line=model_line
    )
    path.write_text(body)
    try:
        os.chmod(path, 0o755)
    except OSError:
        pass
    return path


# ---------------------------------------------------------------------------
# Lazy import of Hermes' cron API


def _import_cron():
    """Import ``cron.jobs`` only when called — keeps tests / pip install lean."""
    try:
        from cron import jobs as cron_jobs  # type: ignore[import-not-found]
        return cron_jobs
    except ImportError as exc:  # pragma: no cover — only triggered outside Hermes
        raise RuntimeError(
            "Hermes cron module unavailable. botcoin_autostart / botcoin_autostop "
            "must run inside the Hermes runtime (gateway, CLI session). For "
            "scheduling outside Hermes, use cron(8) or systemd directly with "
            "`hermes-botcoin-mine`."
        ) from exc


# ---------------------------------------------------------------------------
# Public API used by tools.py


def find_existing_job() -> dict | None:
    cron_jobs = _import_cron()
    jobs = cron_jobs.list_jobs(include_disabled=True)
    for job in jobs:
        if job.get("name") == JOB_NAME:
            return job
    return None


def autostart(
    *,
    schedule: str = "every 90s",
    solver: str | None = None,
    model: str | None = None,
    max_per_day: int | None = None,
    deliver: str = "local",
) -> dict[str, Any]:
    """Idempotently create the BOTCOIN cron job. Returns the job dict."""
    cron_jobs = _import_cron()

    existing = find_existing_job()
    if existing:
        return {"created": False, "job": existing, "wrapper": str(_scripts_dir() / SCRIPT_BASENAME)}

    if shutil.which("hermes-botcoin-mine") is None:
        raise RuntimeError(
            "`hermes-botcoin-mine` is not on PATH. Install with `pip install hermes-botcoin` "
            "(adds the console-script entry point) and re-run."
        )

    chosen_solver = (solver or os.environ.get("BOTCOIN_SOLVER_PROVIDER") or "venice").lower()
    if max_per_day is not None:
        os.environ["BOTCOIN_MAX_ATTEMPTS_PER_DAY"] = str(int(max_per_day))

    wrapper = _write_wrapper_script(solver=chosen_solver, model=model, force=False)

    job = cron_jobs.create_job(
        prompt=None,
        schedule=schedule,
        name=JOB_NAME,
        script=str(wrapper),
        no_agent=True,
        deliver=deliver,
        repeat=None,  # forever
    )
    return {
        "created": True,
        "job": job,
        "wrapper": str(wrapper),
        "max_per_day": daily_ceiling(),
    }


def autostop() -> dict[str, Any]:
    """Remove the BOTCOIN cron job. Returns ``{"removed": bool, "job_id": str|None}``."""
    cron_jobs = _import_cron()
    existing = find_existing_job()
    if not existing:
        return {"removed": False, "reason": "no BOTCOIN miner job is currently scheduled"}
    ok = cron_jobs.remove_job(existing["id"])
    return {"removed": bool(ok), "job_id": existing["id"], "name": JOB_NAME}
